version: "3"
services:
  mysql:
    container_name: eventhub_mysql
    command: --default-authentication-plugin=mysql_native_password
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root-pw
      MYSQL_DATABASE: eventhub_db
      MYSQL_USER: set
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    # networks:
      # - eventhub_network


  api:
    container_name: eventhub_api
    build: ./src
    # volumes:
    #   - ./src/node:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    tty: true
    # networks:
    #   - eventhub_network

# networks:
#   eventhub_network:
#     driver: bridge